# encoding: utf-8
require 'open_classes/numeric/dice_back'
require 'open_classes/numeric/dozen'
require 'open_classes/numeric/is_ascii'
require 'open_classes/numeric/to_binary_table'
require 'open_classes/numeric/to_binary_html_table'
require 'open_classes/numeric/to_digit_html_table'
require 'open_classes/numeric/to_digit_table'
require 'open_classes/numeric/to_hex_html_table'
require 'open_classes/numeric/to_hex_table'
require 'open_classes/numeric/to_oct_table'
